CREATE TABLE CUSTOMER(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255),
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100)
);

INSERT INTO CUSTOMER(EMAIL,FIRST_NAME,LAST_NAME) VALUES ('FIRST@FIRST.COM','FIRST','LAST');
commit;

